name = "old-sunset-4710"
main = "worker.js"
compatibility_date = "2025-12-05"
keep_vars = true

[[kv_namespaces]]
binding = "CARD_ORDER"
id = "3908bfd2e95747c697f99396fe2a4357"

[observability]
enabled = true
head_sampling_rate = 1
